firstapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns= [
    path('index/',views.index, name="index"),
    # path('index/',views.Index.as_view(?, name="index")
    path('contact/',views.contact, name="contact"),

    #auth endpoint
    path('signup/',views.RegisterView.as_view(),name='signup'),
    path('session/',views.testsessions,name='sessiontest'),
]

firstproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('firstapp.urls','firstapp'),namespace='firstapp')),
]

firstapp/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

from django.contrib.auth.models import AbstractUser,PermissionsMixin ,AbstractBaseUser
from .managers import CustomUserManager
from django.utils.translation import gettext_lazy as _

# Create your models here.

# class UserType(models.Model):
#     CUSTOMER = 1
#     SELLER = 2
#     TYPE_CHOICES = (
#         (SELLER,'SELLER'),
#         (CUSTOMER,'CUSTOMER')
#     )

#     id = models.PositiveSmallIntegerField(choices=TYPE_CHOICES,primary_key=True)

#     def __str__(self):
#         return self.get_id_display()

# class Customer(models.Model):
#     user = models.OneToOneField(User, on_delete= models.CASCADE)
#     address = models.CharField(max_length=1000)

# class Seller(models.Model):
#     user = models.OneToOneField(User, on_delete= models.CASCADE)
#     tax = models.CharField()
    

class CustomUser(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    # is_customer = models.BooleanField(default=True)
    # is_seller = models.BooleanField(default=False)


    # type = (
    #     (1,'Seller'),
    #     (2,'Customer')
    # )
    # user_type = models.IntegerField(choices = type, default=1)

    #user_type = models.ManyToManyField(UserType)

    class Types(models.TextChoices):
        SELLER= "Seller","SELLER"
        CUSTOMER = "Customer","CUSTOMER"

    default_type = Types.CUSTOMER
    type = models.CharField(_("Type"), max_length=255, choices=Types.choices, default=default_type)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.type = self.default_type
        return super().save(*args,**kwargs)

class CustomerAdditional(models.Model):
    user = models.OneToOneField(CustomUser, on_delete= models.CASCADE)
    address = models.CharField(max_length=10)


class SellerAdditional(models.Model):
    user = models.OneToOneField(CustomUser, on_delete= models.CASCADE)
    tax = models.CharField(max_length=10)
    warehouse_loc = models.CharField(max_length=100)

#model Mangers for proxy models
class SellerManager(models.Manager):
    def get_queryset(self,*args,**kwargs):
        return super().get_queryset(*args,**kwargs).filter(type=CustomUser.Types.SELLER)

class CustomerManager(models.Manager):
    def get_queryset(self,*args,**kwargs):
        return super().get_queryset(*args,**kwargs).filter(type=CustomUser.Types.CUSTOMER)
    
#proxy models.they do not create a seperate table
class Seller(CustomUser):
    default_type = CustomUser.Types.SELLER
    objects = SellerManager()
    class Meta:
        proxy:True

    def sell(self):
        print("I can sell")
    
    @property
    def showAdditional(self):
        return self.selleradditional

class Customer(CustomUser):
    default_type = CustomUser.Types.CUSTOMER
    objects = CustomerManager()
    class Meta:
        proxy:True

    def buy(self):
        print("I can buy")

    @property
    def showAdditional(self):
        return self.customeradditional



class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    prduct_name = models.CharField(max_length=255)
    price = models.FloatField()

    def __str__(self):
        return self.prduct_name
    
    
class Cart(models.Model):
    cart_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    created_on = models.DateTimeField()

class ProductInCart(models.Model):
    class Meta:
        unique_together=(('cart','product'),)
    product_in_cart_id = models.AutoField(primary_key=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

class Order(models.Model):
    status_choices = (
        (1,"Not Packed"),
        (2,"Ready For Shipment"),
        (3,"Shipped"),
        (4,"Delivered")
    )
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    status = models.IntegerField(choices=status_choices,default=1)

class Deal(models.Model):
    user = models.ManyToManyField(CustomUser)
    deal_name = models.CharField(max_length=255)

class Contact(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=10)
    phone = models.IntegerField()
    query = models.TextField()

firstapp/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django import forms
from .models import CustomUser,Contact

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class ContactForm(forms.ModelForm):
    # email = forms.EmailField(required=True)
    # name = forms.CharField(max_length=10,required=True)
    # # regex code
    # regex = None
    # phone = forms.IntegerField(required=True,validator=[regex])
    # query = forms.CharField(widget = forms.Textarea )
    class Meta:
        model = Contact
        fields = [
            'email',
            'phone',
            'query',
            'name'
        ]

class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields =[
            "email",
            "password1",
            "password2"
        ]

firstapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.core.exceptions import ValidationError
from .forms import ContactForm
from django.views.generic.edit import CreateView
from .forms import RegistrationForm



# Create your views here.
def index(request):
    age =10
    arr =['hey','you']
    return render(request,'firstapp/index.html',{"age":age,"arr":arr})

# class Index(TemplateView):
#     template_name = 'firstapp/index.html'
#     def get_context_data(self, **kwargs):
#         age =10
#         arr =['hey','you']
#         context_old = super().get_context_data(**kwargs)
#         context = {"age":age,"arr":arr, " context_old":context_old}
#         return context



#     if request.method == "POST":
#         name = request.POST.get('name')
#         email = request.POST.get('email')
#         # phone = request.POST.get('phone')
#         if len(phone)<10 or len(phone)>10:
#             return ValidationError("Problem with phone number.")
#         phone = request.POST['phone']
#         query = request.POST.get('query')
#     return render(request,'firstapp/contact.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            if len(form.cleaned_data.get('query'))>10:
                form.add_error('query','Query length is not right')
                return render(request,'firstapp/contact.html',{'form':form})
            form.save()
            return HttpResponse("Thank you")
        else:
            if len(form.cleaned_data.get('query'))>10:
                form.add_error('query','Query length is not right')
                form.errors['__all__'] = "query length is not right."
            return render(request,'firstapp/contact.html',{'form':form})
    return render(request,'firstapp/contact.html',{'form':ContactForm})

class RegisterView(CreateView):
    template_name = "firstapp/register.html"
    form_class = RegistrationForm
    success_url = reverse_lazy('index')

def testsessions(request):
    if request.session.get('test',False):
        print(request.session['test'])

    request.session.set_expiry(1)
    request.session['test'] = 'hello'
    return render(request,'firstapp/sessiontesting.html')

firstapp/templates/firstapp/basic.html
<!doctype html>
<html lang="ar" dir="rtl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU" crossorigin="anonymous">

    <title> {% block title %}{% endblock %} </title>
    {% block css %}{% endblock %}
  </head>
  <body>
        <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
            {% comment %} Dynamic URL {% endcomment %}
              <a class="nav-link" href="{% url "firstapp:contact"%}">Contact Us</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
      </nav>
      {% block body %}

      {% endblock%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    -->
  </body>
  {% block js %} 
  {% endblock %}
</html>

firstapp/templates/firstapp/contact.html
{% extends 'firstapp/basic.html' %}
{% load static%}
{% block title %}
{% endblock %}
{% block css %}
{% endblock %}
{% block body %}
<div class="container">
{{form.as_p}}
 </div>
{% endblock%}

firstapp/templates/firstapp/register.html
{% extends 'firstapp/basic.html' %}
{% load static%}
{% block title %}
{% endblock %}
{% block css %}
{% endblock %}
{% block body %}
<div class="container">
<form method= "POST">{% csrf_token %}
{{form.as_p}}
<button type='submit' class='btn btn-primary'> Signup </button>
</form>
 </div>
{% endblock%}

firstapp/templates/firstapp/sessiontesting.html
<h1>hello</h1>